backend:
  name: git-gateway
  branch: main  # Use your main branch here

media_folder: "static/img"  # Where uploaded media will go
public_folder: "/img"

collections:
  - name: "pages"  # This is the name of the collection
    label: "Pages"  # Display name for the collection in the CMS
    folder: "content/pages"  # The folder where markdown files are stored
    create: true  # Allow new pages to be created
    slug: "{{title}}"  # Slug for the page will be based on the title field
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Content", name: "body", widget: "markdown" }
